version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=url_details
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306

  app:
    image: app:latest
    ports:
       - 8084:8084
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-stand:3306/url_directory?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    depends_on:
       - docker-mysql